# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8ca30b0f5bfc04075532d31f3b4ed94c080462d064817f13275094e15250340b5001cf6301bbb95a5bc2525a888dd0b5d5885c81d1aebc9ef7050902bcea669

test:
  secret_key_base: 05b27e5d9d74ce2050e57b74ef7ea28d71be3e6075e229987db2da8ef5421fde49e9277baf51b1e06e03c2e776d0aab8338b70df87930b83d0df0d4e65d3df1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
